spring:
  mvc:
    contentnegotiation:
      favor-parameter: false
      media-types:
        json: application/json
        xml: application/xml
        yaml: application/x-yaml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_certacon
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show-sql: false
  flyway:
      baselineOnMigrate: true
  logging:
    level:
       org.springframework: DEBUG
       debug: true
  spring-doc:
      pathsToMatch: /api/**/v1/**
  springdoc:
    swagger-ui:
      path:
        /swagger-ui.html
  swagger-ui:
    user-root-path: true